In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("/content/preprocessing_dataset.csv")
df

      Name    Age Gender   Salary Department
0    Alice   25.0      F  50000.0         HR
1      Bob   30.0      M  60000.0    Finance
2  Charlie    NaN      M  55000.0         IT
3    David   40.0      M  58000.0         HR
4      Eve   22.0      F  52000.0         IT
5    Frank   35.0    NaN  61000.0    Finance
6    Grace  120.0      F      NaN    Finance
7    Henry   28.0      M  59000.0         HR
8      Ivy   29.0      F  63000.0         IT
9     Jack   27.0      M  62000.0    Finance

In [ ]:
df1=df.copy()
df2=df.copy()
df3=df.copy()

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df1['Gender_encoded']=le.fit_transform(df1['Gender'])
df1

      Name    Age Gender   Salary Department  Gender_encoded
0    Alice   25.0      F  50000.0         HR               0
1      Bob   30.0      M  60000.0    Finance               1
2  Charlie    NaN      M  55000.0         IT               1
3    David   40.0      M  58000.0         HR               1
4      Eve   22.0      F  52000.0         IT               0
5    Frank   35.0    NaN  61000.0    Finance               2
6    Grace  120.0      F      NaN    Finance               0
7    Henry   28.0      M  59000.0         HR               1
8      Ivy   29.0      F  63000.0         IT               0
9     Jack   27.0      M  62000.0    Finance               1

In [ ]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder(sparse_output=False)
encoded = one.fit_transform(df2[['Gender']])
df2[['Male','Female']] = encoded
df2

,Name,Age,Gender,Salary,Department,Gender_encoded,Female,Male
0,Alice,25.0,1.0,50000.0,HR,<Compressed Sparse Row sparse matrix of dtype ...,1.0,0.0
1,Bob,30.0,0.0,60000.0,Finance,<Compressed Sparse Row sparse matrix of dtype ...,0.0,1.0
2,Charlie,NaN,0.0,55000.0,IT,<Compressed Sparse Row sparse matrix of dtype ...,0.0,1.0
3,David,40.0,0.0,58000.0,HR,<Compressed Sparse Row sparse matrix of dtype ...,0.0,1.0
4,Eve,22.0,1.0,52000.0,IT,<Compressed Sparse Row sparse matrix of dtype ...,1.0,0.0
5,Frank,35.0,0.0,61000.0,Finance,<Compressed Sparse Row sparse matrix of dtype ...,0.0,1.0
6,Grace,120.0,1.0,NaN,Finance,<Compressed Sparse Row sparse matrix of dtype ...,1.0,0.0
7,Henry,28.0,0.0,59000.0,HR,<Compressed Sparse Row sparse matrix of dtype ...,0.0,1.0
8,Ivy,29.0,1.0,63000.0,IT,<Compressed Sparse Row sparse matrix of dtype ...,1.0,0.0
9,Jack,27.0,0.0,62000.0,Finance,<Compressed Sparse Row sparse matrix of dtype ...,0.0,1.0

In [ ]:
df3=df.copy()
df3=pd.get_dummies(df3,columns=['Gender'],drop_first=False)
df3

      Name    Age   Salary Department  Gender_F  Gender_M
0    Alice   25.0  50000.0         HR      True     False
1      Bob   30.0  60000.0    Finance     False      True
2  Charlie    NaN  55000.0         IT     False      True
3    David   40.0  58000.0         HR     False      True
4      Eve   22.0  52000.0         IT      True     False
5    Frank   35.0  61000.0    Finance     False     False
6    Grace  120.0      NaN    Finance      True     False
7    Henry   28.0  59000.0         HR     False      True
8      Ivy   29.0  63000.0         IT      True     False
9     Jack   27.0  62000.0    Finance     False      True

In [ ]:
#PLDAY4 continued as lungcancer in another notebook